### ISSUE TITLE
Dependency vulnerability (npm audit)

### ISSUE THREAD

**Issue by yairkukielka** [kentcdodds/babel-plugin-macros#107]
* `babel-plugin-macros` version: 2.5.0
* `node` version: any
* `npm` (or `yarn`) version: any

Relevant code or config

What you did: run `npm audit`

What happened:

![advisory](https://user-images.githubusercontent.com/11599360/55244954-65539e80-51ff-11e9-9105-267bc0be2b52.png)

Problem description: npm advisory due to vulnerability: https://www.npmjs.com/advisories/788

Suggested solution: release new version with the dependency cosmiconfig version number bumped to 5.2.0 (minimum)

**Comment by kentcdodds** [comment]
Got everything updated :) A release should go out shortly.
