### ISSUE TITLE
read environment specific config

### ISSUE THREAD

**Issue by codepunkt** [kentcdodds/babel-plugin-macros#108]
It would be great if babel-plugin-macros could read environment specific configuration the way babel does, e.g. using `styled-components` macro with this configuration in `package.json` would then use `{ displayName: true}` unless in production, where it would use `{ displayName: true }`

```json
{
  "babelMacros": {
    "styledComponents": {
      "displayName": true,
      "env": {
        "production": {
          "displayName": false
        }
      }
    }
  }
}
```

What do you think?

**Comment by kentcdodds** [comment]
Hi @codepunkt!

I never liked that feature in babel's config because I always found it confusing. Instead, I recommend folks use the js variant.

```javascript
// babel-plugin-macros.config.js
module.exports = {
  styledComponents: {
    displayName: process.env.NODE_ENV !== 'production'
  }
}
```

I much prefer this in my own babel config and I don't want to create a DSL for something so simple. Thanks anyway!

**Comment by codepunkt** [comment]
@kentcdodds thanks! 👍
