### ISSUE TITLE
Test suite fails on Windows

### ISSUE THREAD

**Issue by InvictusMB** [kentcdodds/babel-plugin-macros#115]
* `babel-plugin-macros` version: 2.5.1
* `node` version:  both 8.x and 10.x
* `npm` version: 6.9.0

What you did:

`npm test`

What happened:

```
λ npm test

> babel-plugin-macros@0.0.0-semantically-released test C:\Projects\babel-plugin-macros
> kcd-scripts test
 PASS  src/__tests__/create-macros.js
 FAIL  src/__tests__/index.js
  ● Test suite failed to run

    Cannot find module 'babel-plugin-macros-test-fake/macro' from 'C:\Projects\babel-plugin-macros\src\__tests__'

      at Function.module.exports [as sync] (node_modules/resolve/lib/sync.js:69:15)
      at nodeResolvePath (node_modules/babel-plugin-macros/dist/index.js:49:18)
      at applyMacros (node_modules/babel-plugin-macros/dist/index.js:178:23)
      at VariableDeclaration.path.get.filter.forEach.child (node_modules/babel-plugin-macros/dist/index.js:126:30)
          at Array.forEach (<anonymous>)
      at VariableDeclaration (node_modules/babel-plugin-macros/dist/index.js:116:55)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
```

Problem description:

As mentioned in #111, the test suite fails on Windows.

I did a bit of troubleshooting and these are the findings:

* `mock-modules` are not present in the `node_modules` directory when `resolve.sync` for `'babel-plugin-macros-test-fake/macro'` fails 
* most likely `beforeAll` hook is not executed and the `mock-modules` are not copied properly

Now goes the funny part. I don't have a slightest idea what the execution model of the test code is and what kind of black magic happens there.

These are the things I don't get:

* Why does it fail inside the `babel-plugin-macros` code within `node_modules` and not the inside `src` directory?

* Why does it fail with the same error even if I add `throw new Error('In global scope!');` on top of `src/__tests__/index.js`?

* Why does it fail with the expected error if I add `throw new Error('In global scope!');` on top of `src/__tests__/index.js` and comment out the entire `pluginTester` invocation?

* Why wouldn't this happen in other environments?

**Comment by InvictusMB** [comment]
This gets weirder and weirder.

So it seemed that I had found the offending code by pure serendipity:
https://github.com/kentcdodds/babel-plugin-macros/blob/97cdfdd69a03dff4a76d84f1bdb0d97cbd576482/other/babel-config.js#L10-L11

I did a quick fix for OS dependent path separators:
```es6
        !pluginPath.includes('babel-macros' + path.sep) &&
        !pluginPath.includes('babel-plugin-macros' + path.sep),
```
The test suite was passing and everything was fine. The memory is fading away quickly but I want to believe that it did pass at least once and everything was fine.

Then I rebased against the latest changes, wiped the `node_modules`, rerun the tests and got a few failures.
Went back to 2.5.1 tag and from then on I could no longer reproduce the original issue.

The test suite does not execute the config anymore. I've verified that it loads the config file but never invokes the exported function.

```es6
// babel-plugin-macros/other/babel-config.js
const getBabelConfig = require('kcd-scripts/babel')

console.log('babel-config init') // This gets printed
module.exports = (...args) => {
  console.log('babel-config execute') // This never gets printed
  const babelConfig = getBabelConfig(...args)

  /* ... */
}
```

These are the failing tests:
```
    × macros can set their configName and get their config (168ms)
    × when there is an error reading the config, a helpful message is logged (9ms)
    × when there is no config to load, then no config is passed (5ms)
```

There are 2 similar failures like this:
```
 ● macros › macros can set their configName and get their config

    expect(jest.fn())[.not].toHaveBeenCalledTimes()

    Matcher error: received value must be a mock or spy function

    Received has value: undefined

      261 |         const babelMacrosConfig = require('./fixtures/config/babel-plugin-macros.config')
      262 |         const configurableMacro = require('./fixtures/config/configurable.macro')
    > 263 |         expect(configurableMacro.realMacro).toHaveBeenCalledTimes(1)
          |                                             ^
      264 |         expect(configurableMacro.realMacro).toHaveBeenCalledWith(
      265 |           expect.objectContaining({
      266 |             config: babelMacrosConfig[configurableMacro.configName],

      at toHaveBeenCalledTimes (src/__tests__/index.js:263:45)
      at node_modules/babel-plugin-tester/dist/index.js:147:24
          at Array.map (<anonymous>)
      at Object.<anonymous> (node_modules/babel-plugin-tester/dist/index.js:146:43)
      at asyncGeneratorStep (node_modules/babel-plugin-tester/dist/index.js:21:103)
      at _next (node_modules/babel-plugin-tester/dist/index.js:23:194)
```
And one snapshot failure:
```
 ● macros › when there is an error reading the config, a helpful message is logged

    expect(received).toMatchSnapshot(hint)

    Snapshot name: `macros when there is an error reading the config, a helpful message is logged: when there is an error reading the config, a helpful message is logged 1`

    - Snapshot
    + Received

    @@ -3,6 +3,6 @@
      // eslint-disable-next-line babel/no-unused-expressions
      configured`stuff`
      
            ↓ ↓ ↓ ↓ ↓ ↓
      
    - Error: this is a cosmiconfig error
    + Error: https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md#writing-a-macro

      at tester (node_modules/babel-plugin-tester/dist/index.js:191:44)
      at Object.<anonymous> (node_modules/babel-plugin-tester/dist/index.js:143:13)
      at asyncGeneratorStep (node_modules/babel-plugin-tester/dist/index.js:21:103)
      at _next (node_modules/babel-plugin-tester/dist/index.js:23:194)
```

Dunno where to go from here.

**Comment by InvictusMB** [comment]
@kentcdodds 
Although it works now I still smell something fishy here.
The 3 tests mentioned were failing because after the cleanup I just run `npm test` which does not perform `npm run build` step.
So if I remove the `dist` folder then `npm test` fails and if I do `npm run build` it does not.
This makes no sense to me as the tests are always run from `src/__tests__` and I don't see any references to `dist` anywhere.

Why would `dist` folder presence matter here?

There are also some impurities in test execution introduced by `jest` and something else.
I could not reproduce the original issue because of Jest cache.

But wiping Jest cache alone was not enough.
After `npx jest --clearCache` I get another weird error:
```
λ npm test

> babel-plugin-macros@0.0.0-semantically-released test C:\Projects\babel-plugin-macros
> kcd-scripts test
No tests found related to files changed since last commit.
Press `a` to run all tests, or run Jest with `--watchAll`.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.
 FAIL  src/__tests__/index.js
  ● Test suite failed to run

    ReferenceError: jest is not defined

      at Object.<anonymous> (node_modules/babel-plugin-macros-test-fake/macro.js:4:17)
      at interopRequire (node_modules/babel-plugin-macros/dist/index.js:80:15)
      at applyMacros (node_modules/babel-plugin-macros/dist/index.js:201:17)

 PASS  src/__tests__/create-macros.js

Test Suites: 1 failed, 1 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   2 passed, 2 total
Time:        2.543s
Ran all test suites.
```
It does go away only if I do both `npx jest --clearCache` and wipe the `node_modules`.

What else could do any caching here?

**Comment by kentcdodds** [comment]
That is odd 🤔

The testing situation in this project is a little tricky 😬
