### ISSUE TITLE
Getting The macro imported from "./test.macro" must be wrapped in "createMacro" in simple example using create-react-app

### ISSUE THREAD

**Issue by mikeaustin** [kentcdodds/babel-plugin-macros#126]
* `babel-plugin-macros` version: ^2.6.1
* `node` version: 11.12.0
* `npm` (or `yarn`) version: 6.7.0

Relevant code or config

```javascript
const createMacro = require('babel-plugin-macros')

function testMacro({ references, state, babel }) {
  console.log(references)
}

module.exports = createMacro(testMacro)
```

What you did:

Saved the source above as test.macro.js, and imported it in index via import test from './test.macro'.

What happened:

Error: The macro imported from "./test.macro" must be wrapped in "createMacro" which you can get from "babel-plugin-macros". Please refer to...

Reproduction repository:

https://github.com/mikeaustin/macro-test

Problem description:

It seems simple enough, but it's complaining that the macro is not wrapped in createMacro, when it clearly is.

Suggested solution:

It might just be documentation. There docs are elaborate, but don't show the simplest complete example, writing the macro, importing it, and using it, in one place.

**Comment by kentcdodds** [comment]
I think you haven't pushed your latest changes. There are no macros in that repo.

**Comment by kentcdodds** [comment]
In any case, the issue is this:

```diff
- const createMacro = require('babel-plugin-macros')
+ const {createMacro} = require('babel-plugin-macros')
```

**Comment by kentcdodds** [comment]
Here's a working demo: https://github.com/kentcdodds/cra-macro-example
