### ISSUE TITLE
Is it possible to curry a macro?

### ISSUE THREAD

**Issue by TomerAberbach** [kentcdodds/babel-plugin-macros#128]
First of all, I want to thank you for making this awesome package!

I've created a function macro which takes some number of arguments and I'd like to give users the ability to "curry" the macro (i.e. set defaults for some of the arguments) and put it in their own module.

For example, normal usage (no currying) would look like this:
`first.js`
```js
import myMacro from 'mymacro.macro'

myMacro({ a: 1, b: 2 })
```

And with currying:
`second.js`
```js
import { curryMyMacro } from 'mymacro.macro'

export default curriedMacro = curryMyMacro({ a: 1 })
```
`third.js`
```js
import curriedMacro from 'second'

// 'a' is 1
curriedMacro({ b: 2 })
```

However, I'm not sure how I would accomplish this. It seems that it would require creating macro which creates a macro, involving a second macro pass, or somehow getting the references of `curriedMacro`. Any ideas?

**Comment by kentcdodds** [comment]
Sorry, I'm not sure I understand the use case, but you need to remember that macros are only applicable during compilation and can not determine any runtime values reliably.

**Comment by TomerAberbach** [comment]
Let me see if I can clarify my use case. I would like to give users of my macro the option of currying/fixing some of the parameters of the macro to specific values at compile-time. However, I would like to give them the opportunity to create several versions of the macro (with each version fixing parameters to different values).

Reading through your docs again I'm thinking this might be possible using the experimental macro configuration file. For example, if I made a macro taking an object type: `{ a: number, b: number }` then maybe the user of the macro could specify curried/fixed versions of the macro in the macro configuration file like so:
```json
{
  "versions": [
    {
      "name": "myFirstCurriedMacro",
      "fixedArguments": { "a": 3 }
    },
    {
      "name": "mySecondCurriedMacro",
      "fixedArguments": { "b": 1 }
    }
  ]
}
```

So now the user would be able to call all three versions of the macro like so:
```js
import { myMacro, myFirstCurriedMacro, mySecondCurriedMacro } from 'mymacro.macro'

myMacro({ a: 1, b: 2 }) // need to provide all arguments
myFirstCurriedMacro({ b: 2 }) // only need to provide `b` because `a` is fixed to 3 as specified in the configuration file
mySecondCurriedMacro({ a: 1 }) // only need to provide `a` because `b` is fixed to 1 as specified in the configuration file
```

Does this seem like a reasonable approach? Since the macro configuration file is experimental, should I hold off on doing something like this?

**Comment by kentcdodds** [comment]
You can assume the config is stable. I should update the docs about that. I think we're pretty committed to the config now.

You can go ahead and do that if you want, but I personally think it would make things confusing to do too much of that.

Good luck!
