### ISSUE TITLE
False positive in macrosRegex

### ISSUE THREAD

**Issue by longlho** [kentcdodds/babel-plugin-macros#131]
We recently released `@formatjs/macro` and got this issue https://github.com/formatjs/react-intl/issues/1511 for a user. The macro we use is not compatible with babel-plugin-macros because we use that in TS transformer & eslint as well so we don't wrap it, but it looks like babel-plugin-macros might be too aggressive and throw an error if it detects anything that looks like `macrosRegex`. My suggestion: Can we turn this into a warning?

**Comment by kentcdodds** [comment]
Just to make sure I understand... Are *users* importing `@formatjs/macro` or is that an import you have internally? If internally, then maybe you can just tell users to not compile dependencies with babel?

**Comment by longlho** [comment]
It is an import I have internally. Some people compile `react-intl` because we do distribute esnext (e.g for CEF/Electron app). webpack unfortunately pick that up automatically so it's a cascading toolchain problem.

**Comment by kentcdodds** [comment]
Is there any reason you can't change the filename? I don't think changing this to a warning will help things much.

**Comment by longlho** [comment]
it's a package name, which I'm less inclined to change :( We store other macros in there basically. Changing to a warning would not crash the compilation pipeline. I assume there are some checks besides just filename to see if this is really a babel macros?

**Comment by futagoza** [comment]
What about an option?

IMO, a function that returns true on a positive match would help, and if the default function for this option just wraps `macrosRegex.test`, this would be a non-breaking change (a minor release).

**Comment by kentcdodds** [comment]
That's reasonable. I'd be willing to accept a pull request for that. 👍

**Comment by futagoza** [comment]
@kentcdodds Haven't worked on a Babel plugin before, but now's a good time as any I guess 😅

Just a couple of things:

1. I'm thinking of using `isMacrosName` for the option/function name; Is this fine with you?
2. This should be destructed [before `...options` in the `macrosPlugin` parameter list](https://github.com/kentcdodds/babel-plugin-macros/blob/master/src/index.js#L71), right?
3. Looking at [the current tests](https://github.com/kentcdodds/babel-plugin-macros/blob/master/src/__tests__/index.js#L373), should I use `pluginOptions` to help test this?

**Comment by kentcdodds** [comment]
Sorry, I think babel-plugin-tester has a transitive dep change that messed things up. I'll try to look into it as soon as I'm able.

**Comment by futagoza** [comment]
@longlho The new `isMacrosName` option in `2.7.0` resolves this now; confirm it before closing this?

**Comment by longlho** [comment]
@tdeekens reported it so I can't really confirm :( it's a transient issue to me.

**Comment by kentcdodds** [comment]
It's solved, so I'll go ahead and close this now. Thanks @futagoza!

**Comment by tdeekens** [comment]
Thanks everybody :)

**Comment by AndyOGo** [comment]
@kentcdodds 
I couldn't find any documentation for `isMacrosName()`, neither in [user docs](https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/user.md), nor [author docs](https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md).

**Comment by AndyOGo** [comment]
Alright, to whom it may concerns.

We had to extend our Babel config to supply a custom `isMacrosName()` function.
https://github.com/kentcdodds/babel-plugin-macros/blob/2cac571a5809c42671c2bcbd74921df65036369e/src/index.js#L5-L6

**babel.config.js:**

```js
// Fixes https://github.com/formatjs/react-intl/issues/1511
//       https://github.com/kentcdodds/babel-plugin-macros/issues/131
const macrosRegex = /[./]macro(\.js)?$/;
const testMacrosRegex = v =>
  macrosRegex.test(v) && v.indexOf('@formatjs/macro') === -1;
module.exports = {
  plugins: [
    [
      'macros',
      {
        isMacrosName: testMacrosRegex,
      },
    ],
  ],
};
```

**Comment by thadk** [comment]
What is the resolution to this `react-intl` issue within create-react-app when it is preferred to not modify babel? I just tested and it is still broken for `react-scripts: 3.3.0-next.80`. The mainline repository says they cannot fix: https://github.com/formatjs/react-intl/issues/1511

**Comment by AndyOGo** [comment]
@kentcdodds it can be configured to work now.
But zero config tools like CRA are still broken with react-intl.

I think this check could be improved.
- how if we check the exported funcrion, like expected number of args
- or what actually is exportet
- should babel be part of the file name?
- maybe you see other possible checks?

**Comment by arvinsim** [comment]
This is still broken in CRA. My tests always fails because of this issue.

**Comment by kentcdodds** [comment]
Sorry. There's nothing more we can do in this package. Either get them to change the name of their file or get CRA to alter the config to use the new feature that was added.
