### ISSUE TITLE
Should babel plugin macros be dependencies?

### ISSUE THREAD

**Issue by magicmark** [kentcdodds/babel-plugin-macros#141]
Hi @kentcdodds 👋

Wondering if you could help clear up a bit of confusion over the type of dependency a babel macro should be :)

I see there's been previous discussion here https://github.com/kentcdodds/babel-plugin-macros/issues/53, where although there's nuance involved, it it seems we landed on 'probably dev' - as codified here in the docs: https://github.com/kentcdodds/babel-plugin-macros#should-macros-be-dependencies-or-devdependencies

This came up in the js-lingui project, which uses babel macros for its Translation components: https://github.com/lingui/js-lingui/issues/409,

The issue is that because we import a macro from '@lingui/macro', which is a devDep, we get the following eslint complaint when using `eslint-plugin-import`:

```
[eslint] '@lingui/macro' should be listed in the project's dependencies, not devDependencies. [import/no-extraneous-dependencies]
```

Discussed this with @ljharb here https://github.com/benmosher/eslint-plugin-import/issues/1553#issuecomment-572207961

Seems the more frictionless "default" for macros would be to say "regular dep" as a general rule. Thoughts?

Thank you!

**Comment by kentcdodds** [comment]
There's really no problem just making it a regular dep so feel free to do that. 🤷‍♂️

Maybe I'll just remove that section from the docs and let people decide what they want to do themselves. It doesn't typically make much of a difference.
