### ISSUE TITLE
Is it possible to import and re-export a macro?

### ISSUE THREAD

**Issue by sanjaypojo** [kentcdodds/babel-plugin-macros#142]
We tried to import a macro and then export it out again and we get a compile time error. Is this expected?

To reproduce, this throws an error at compile time:
```javascript
import {t} from "@lingui/macro"

export {t}
```

But we don't have any errors if we directly use the macro:
```javascript
import {t} from "@lingui/macro"

const text = t`Hello`
```

**Comment by tricoder42** [comment]
Hey @sanjaypojo, TLDR: I don't think this is supposed to work.

It would be very complicated to track the origin on macro function. Right now when compiler sees `import ... from "my.macro"`, it simply loads the macro function from `my.macro` package (at compiler level). If you look inside the `@lingui/macro` package, there's no `t` export. Just default export of `creteMacro(...)` call.

Why do you want to re-export the macro in the first place? Feel free to move the discussion to LinguiJS repository. The bottom line is, re-exporting of macros isn't supported at the moment.

**Comment by sanjaypojo** [comment]
That makes sense @tricoder42 
When we initially used the `@lingui/macro` package, we didn't realize that it was using the compile time magic `babel-plugin-macros` provides, so we were surprised that we couldn't re-export something we had imported. Read up more about what your library does -- very cool and totally understand why we can't re-export!
