### ISSUE TITLE
Make "Learn more: xxx" optional

### ISSUE THREAD

**Issue by ben-rogerson** [kentcdodds/babel-plugin-macros#145]
During errors, I don't want the 'learn more' text to display.
This is because I'm already supplying information on how to resolve the error. 

Could we please make it optional? (I'd rather not have to use MacroError everywhere)

https://github.com/kentcdodds/babel-plugin-macros/blob/2cac571a5809c42671c2bcbd74921df65036369e/src/index.js#L251

**Comment by kentcdodds** [comment]
Hi @ben-rogerson. It is optional. You need to throw a MacroError so we know you've handled it. Otherwise we assume you haven't.

For more on this: https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md#throwing-helpful-errors

**Comment by ben-rogerson** [comment]
Got it, cheers!
