### ISSUE TITLE
Macros are not applied if they are not the default export

### ISSUE THREAD

**Issue by vedantroy** [kentcdodds/babel-plugin-macros#151]
- `babel-plugin-macros` version: 2.8.0
- `node` version: 13.9.0
- `npm` (or `yarn`) version: 6.14.4

Relevant code:

src/macro.js (this file is compiled to "dist/macro.js" with "@babel/plugin-transform-modules-commonjs"):

```javascript
import { createMacro } from "babel-plugin-macros"

function gemmafyMacro({references, state, babel}) {
  references.default.forEach(referencePath => {
      // do macro stuff
  })
}

export default createMacro(gemmafyMacro)
const gemmafyCopy = createMacro(gemmafyMacro)
export {gemmafyCopy}
```

test.js:

```javascript
// compiled with the plugins: 
// babel-plugin-macros, @babel/plugin-transform-modules-commonjs
import gemmafy, {gemmafyCopy} from '../dist/macro'

gemmafy("Hello World");
gemmafyCopy("Hello World");
```
test_compiled.js:
```javascript
"use strict";

"Hello \uD83D\uDC36 World";
gemmafyCopy("Hello World"); // the macro was not applied here
```
What happened:

Only `gemmafy` was applied. `gemmafyCopy` was not applied.

Reproduction repository: https://github.com/vedantroy/babel-plugin-macros-repro

Run `npm run build-macro` and then `npm run build-test`. Then look at `test_compiled.js` in the "tests" folder. You will see that only 1 of the macros has been applied.

Problem description:

Macros are not applied, unless they are the default export?

Suggested solution: Not sure. If this is a bug, I'd be willing to look into a PR.

**Comment by kentcdodds** [comment]
Hi @vedantroy,

The macro must be the default export. If you want to transform non-default exports then use the `references` object.

```javascript
import { createMacro } from "babel-plugin-macros"

function gemmafyMacro({references, state, babel}) {
  references.default.forEach(referencePath => {
      // do macro stuff
  })
  references.gemmafyCopy.forEach(referencePath => {
      // do macro stuff for the named import
  })
}

export default createMacro(gemmafyMacro)
```

See [the documentation](https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md) for more info.

**Comment by vedantroy** [comment]
Oh, I'm silly! I should get better at reading docs :facepalm:
