### ISSUE TITLE
webpack 5 build error 

### ISSUE THREAD

**Issue by mickdelaney** [kentcdodds/babel-plugin-macros#174]
- `babel-plugin-macros` version: ^3.0.1
- `node` version: v15.4.0
- `npm` version: 7.0.15

Relevant code or config

```javascript 

```

What you did:
I'm trying to setup react, typescript with relay using webpack 5. 
I've done this successfully with CRA, but wanted a more customizable config, and also am assessing if i can move to webpack 5.
All goes well until i add relay, which relies on babel-plugin-macros. 

NOTE: I've attempted to polyfill node for webpack 5.

https://github.com/mickdelaney/react-webpack-5-ts-relay/blob/master/webpack.config.js#L15

What happened:

the full build error is here:
https://gist.github.com/mickdelaney/65cedc2e131a1e45edec18a4fb39c68d

Reproduction repository:

https://github.com/mickdelaney/react-webpack-5-ts-relay

Problem description:

Suggested solution:

I'm not an expert on these tools, so am considering just waiting a few months assuming things will stabilize with webpack 5 etc.

**Comment by apuntovanini** [comment]
Can confirm same issue with relay as well, but it came out when I added a dependency which also relies on babel-plugin-macros (twin.macro in particular)

**Comment by mickdelaney** [comment]
fix, i've sort of figured out where i was going wrong. 

a few things: https://github.com/mickdelaney/react-webpack-5-ts-relay/compare/fix-issue

happy to close this now.

**Comment by conartist6** [comment]
Hmm, can you leave a quick summary of what you learned here in case it helps future users?

**Comment by mickdelaney** [comment]
Sure. Will do. Probably Monday/Tuesday. Friday Evening time here 😉

**Comment by conartist6** [comment]
Closing this since it appears to be inactive. If anyone else encounters this problem bug @mickdelaney 😃
