### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by rishu605** [kentcdodds/babel-plugin-macros#187]
I have been setting up swc with webpack. There is a package I use for linting -- eslint-config-react-app. This has a dependency on babel-plugin-macros. I get the following warning on starting the dev server. 

Webpack version is 5.75
`
WARNING in ./node_modules/babel-plugin-macros/dist/index.js 75:22-29
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
`
Looks like it is caused due to the way require is being used in this plugin. Not sure how to get rid of this warning.

- `babel-plugin-macros` version: 3.1.0
- `node` version: 18.12.1
- `npm` version: 8.19.2

I removed all dependencies of babel and it's related packages to avoid any potential conflicts between swc and babel but the warning is still present.

**Comment by conartist6** [comment]
It's most likely the way babel-plugin-macros loads cosmiconfig...

**Comment by conartist6** [comment]
https://github.com/kentcdodds/babel-plugin-macros/blob/8fc6383ef04f628d0b799a9b281c5fc0693b25ac/src/index.js#L26-L27

**Comment by rishu605** [comment]
The error message leads to this line in the code: 
![Screenshot from 2022-12-11 22-15-21](https://user-images.githubusercontent.com/16971746/206916813-74db7835-3913-4dea-83b1-c0a8e4a8960c.png)

**Comment by rishu605** [comment]
Looks like ignoring this warning won't cause any issues for now. Not sure though.

**Comment by conartist6** [comment]
I'm pretty sure that ignoring it won't cause issues. The warning clearly seems to be about the ability to extract the dependency graph, which is not affected.

It does seem suspicious to me though that webpack would be parsing `eslint-config-react-app`. Why is a linter in the bundle?

**Comment by rishu605** [comment]
Is there a way to prevent linting packages from being parsed while bundling through webpack!!

**Comment by conartist6** [comment]
I don't know, because I don't know why it is parsing them.

**Comment by GuYounes** [comment]
Any news ?

**Comment by conartist6** [comment]
No news, unless webpack offers some kind of special comment that silences that warning?
