### ISSUE TITLE
Discussion: set a global that specifies if executed by babel-macros

### ISSUE THREAD

**Issue by CompuIves** [kentcdodds/babel-plugin-macros#3]
I really like this project, thanks a lot for creating this so quickly @kentcdodds!

I have a suggestion for creating a global that's true when a macro is executed in `babel-macros` context.

If you set a global like `module.macro` (like `module.hot`) the dependency has the choice what code path to execute.

I think this will be beneficial for dependencies that have optional macros. For example for `styled-components`, `styled-components` could be completely run in runtime, but also has an option for compile time if `babel-macros` is installed.

Curious what others think about this 😄 .

**Comment by kentcdodds** [comment]
I'm not 100% certain I understand, could you give me an example of code that would leverage a feature like this?

**Comment by CompuIves** [comment]
Ah, I just saw your implementation with `babel-plugin-preval`. This suggestion is not necessary since you already export the functions `asTag`, `asFunction` and `asJSX`.

I was thinking about a way to let dependencies use `babel-macros` optionally, as in, they could detect if the code is executed at compile time or in browser and adjust their exports based on that. But if you export those functions you can already run the functions based on what is exported.

Example:

```js
function asFunction() {
  // Code that will only run at compile time if `babel-macros` is installed
}

function compileAtRuntime() {
  // Code that will be executed if `babel-macros` is not installed
}

module.exports = {
  asFunction,
  default: compileAtRuntime
}
```

**Comment by kentcdodds** [comment]
Ah, gotcha.

So, to be clear, currently the way that `babel-macros` works is it applies when you import something matching [this regex](https://github.com/kentcdodds/babel-macros/blob/fc035ccae3a3651717e675b53a7078c87803fe87/src/index.js#L4)

```javascript
const macrosRegex = /[./]macros(\.js)?$/
```

So it's pretty much a given that your export will _only_ run at build-time and the import/require of the macros is actually removed as part of the compilation as well.

I hadn't considered having a single module that could work at compile time _or_ at runtime. But it could theoretically work! People would just be importing something ending in `macros` which might seem odd to them if they're not using `babel-macros`.

We could change the way things are imported though :)

**Comment by CompuIves** [comment]
Yes you're right. I remember that it took me a while when learning Ruby on Rails what was actually executed in the browser and what was executed on the server. Maybe this isn't really the same, but I imagine that people will get confused when they assume that everything is executed in the browser.

The most obvious ways I can think of are to either change the syntax of the import (`import macro css from 'glamor'`) or by changing how the file is resolved (`import css from 'macro(glamor)'`). This will make a clear distinction.

I could open an issue for discussion for this if want to. 😄

**Comment by kentcdodds** [comment]
Yes, I know that @gaearon was also interested in making sure it was more clear that this is not normal JS stuff.

**Comment by Justineo** [comment]
@kentcdodds First of all, great project!

I've come across a use case of this feature request.

We are implementing a component library and recently we plan to allow users to specify the class prefix of our HTML output. eg. `foo-button` &rarr; `bar-button`. So we are gonna create a helper function and do some codemod like (pseudo code):

```js
import c from './prefixify.macro'

export default function render () {
  return '<div class="' + c`button` + '">Click</div>' // → class="foo-button"
```

As we allow users to import our source code and let their project compile with our code together, so if they haven't configured `babel-plugin-macros`, this would be a breaking change to our library users. If we can conditionally choose different code paths to either generate prefixed string or do AST transformation, the change would be transparent to our users, while they can do further optimization after they introduce `babel-plugin-macros`. So we need to somehow know whether current environment is runtime or build time. Do you have any ideas?

**Comment by Justineo** [comment]
On a second thought, implementing the runtime helper and AST transformation in a single module may not be the best idea. `babel-plugin-macros` will be packed into runtime code, which may leads to further problems.

What about let user specify the pattern of those runtime helpers that also offer a macro implementation? eg. we can add a plugin option `include` (works like the `include` option of Babel):

```json
{
  "plugins": [
    [
      "macros",
      {
        "include": [
          "prefixify"
        ]
      }
    ]
  ]
}
```

So that in source code we can just use:

```js
import c from './prefixify'

export default function render () {
  return '<div class="' + c`button` + '">Click</div>' // → class="foo-button"
}
```

And then `babel-plugin-macros` will look for `prefixify.macro.js` for the transformer implementation at compile time. As long as we provide both `prefixify.js` and `prefixify.macro.js`, the code will run in both runtime and compile time.

**Comment by kentcdodds** [comment]
Hi @Justineo,

I'm afraid that's out of scope for this project. But you could implement your plugin in a way that supports what you're trying to do. Good luck!
