### ISSUE TITLE
What is the recommended way to report a macro misuse error ?

### ISSUE THREAD

**Issue by max-l** [kentcdodds/babel-plugin-macros#43]
I'm writing a macro with babel plugun macro (cool project btw !)
I use it within the rollup.js bundler.

If I encounter misusage of the macro I would like to report the error,
If I just throw an exception, rollup just exists without any message to the console.

I also tried throwing the  exception using this method : 

https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#-throwing-a-syntax-error

and it also exists with no error message in the console.

**Comment by kentcdodds** [comment]
Hmm... Throwing an error is the way I'd recommend. If it doesn't work with Rollup, then we probably need to work on Rollup.

I don't think there's anything we can do 😞

**Comment by kentcdodds** [comment]
I think I'm going to go ahead and close this as it's not actionable in this repository.
