### ISSUE TITLE
Operator macros support?

### ISSUE THREAD

**Issue by aliceklipper** [kentcdodds/babel-plugin-macros#46]
Will it be useful to add operator macros support?

Maybe like this:

````javascript
import { createOperatorMacro, operators } from 'babel-plugin-macros';

const plusMacro = ({ references, state }) => {
    // E.g.
    // Import some function
    // Replace + applications with this function application
};

export default createOperatorMacro(operators.plus, plusMacro);
````

And then:

````javascript
import 'my-plus.macro';

console.log(1 + 2 + 3);
````

Turns into:

````javascript
import { myAwesomeAddition } 'my-awesome-operators';

console.log(myAwesomeAddition(myAwesomeAddition(1, 2), 3));
````

**Comment by kentcdodds** [comment]
Hi @aliceklipper!

Thanks for the interest! I'm going to rope @threepointone (aka "the visionary") into this one to get is take.

From my perspective, I don't think that I want to do this. One of the features of babel-plugin-macros is that the transformations that occur on the codebase are more explicit. I think macros that do this would be a little too much magic and less obvious what's going on.

That said, I would like to hear more about your use case :)

**Comment by threepointone** [comment]
This isn’t explicit and kinda goes against the motivation behind this lib I think. One can’t tell on reading what change is going to happen to the code. Like in the above example you’ve effectively poisoned + for the rest of the module. 

That said, operator overloading is totally useful for expressing some complicated stuff; an example https://github.com/citycide/param.macro similarly I could imagine it being useful to express layout constraint systems, etc. The approach there is better - to use this overloaded syntax within the scope of another explicit macro. So for your original example, you could define a `funkyAdd` macro and then  do `funkyAdd(a +b)`

Would love to hear more about your usecase 

(Typed on phone, sorry for typos)

**Comment by aliceklipper** [comment]
Here an example I find useful.

Input:

````javascript
// eslint-disable-next-line no-unused-vars
import { rightShift, leftShift } from 'my-operators.macro';

const f = x => x ** x;
const g = x => x << x; // macro-disable-line leftShift

const h1 = f >> g;
const h2 = f << g;

console.log(h1(2)); // → 64 === g(f(2))
console.log(h2(2)); // → 16777216 === f(g(x))
````

↑ Here an example of how to control operator macros more explicitly.

We can introduce widely-used by ESLint and some other tools `-disable`/`-enable` comments to control disabling/enabling operator macro or macros for current line, next line, until end of file, until opposite comment.

Output:

````javascript
import {
    pipe as $operatorMacro$myOperators$rightShift,
    compose as $operatorMacro$myOperators$leftShift,
} from 'ramda';

const f = x => x ** x;
const g = x => x << x;

const h1 = $operatorMacro$myOperators$rightShift(f, g);
const h2 = $operatorMacro$myOperators$leftShift(f, g);

console.log(h1(2)); // → 64 === g(f(2))
console.log(h2(2)); // → 16777216 === f(g(x))
````

Macro stub:

````
import { createOperatorMacro, operators } from 'babel-plugin-macros';

const composeMacro = ({ references, state }) => {
    references[operators.rightShift].forEach(ref => {
        //
    });

    references[operators.leftShift].forEach(ref => {
        //
    });
};

export default createOperatorMacro(composeMacro);
````

## Precedence and associativity

I think changing precedence and associativity is much more implicit, than simple operator macros. Also implementing this requires much more effort on code transformations. So I think operators precedence and associativity must be left untouched.

## Operator names

All operator names should be in camel case and named as close as possible to specification.

## Syntax

### Importing

Operator macro should be imported as usual, but imported symbol must have a valid operator name.

**Q:** How to deal with macro, which exposes regular macro named as an operator?

**A:** See __Macro API__ section.

### Application

Operator macro implicitly applies when defined operator used in code.

### Directive comments

`// macro-disable`

Block-scoped directive. Disables all operator macros in current and nested blocks until end of file, `// macro-enable` directive.

Example:

````javascript
import { plus } from 'my.macro';
1 + 1; // Transformed
// macro-disable
2 + 2; // Untouched
3 + 3; // Untouched
````

`// macro-enable`

Block-scoped directive. Enables all imported operator macros in current and nested blocks until end of file, `// macro-disable` directive.

Example:

````javascript
import { plus } from 'my.macro';
1 + 1; // Transformed
// macro-disable
2 + 2; // Untouched
// macro-enable
3 + 3; // Transformed
// macro-disable
4 + 4; // Untouched
// macro-enable
5 + 5; // Transformed
6 + 6; // Transformed
````

`// macro-disable <operator>(, <operator>)*`

Block-scoped directive. Works like `// macro-disable` directive, but disables only specified operator macros in current and nested blocks until end of file, `// macro-enable <operator>(, <operator>)*` directive with corresponding operator name or names, `// macro-enable` directive.

`// macro-enable <operator>(, <operator>)*`

Block-scoped directive. Works like `// macro-enable` and `// macro-disable <operator>(, <operator>)*` directives.

`// macro-disable-line`, `// macro-enable-line`,  
`// macro-disable-line <operator>(, <operator>)*`, `// macro-enable-line <operator>(, <operator>)*`,  

Line-scoped directives. Disable and enable operator macros at current line. Works for all blocks at current line.

`// macro-disable-next-line`, `// macro-enable-next-line`,  
`// macro-disable-next-line <operator>(, <operator>)*`, `// macro-enable-next-line <operator>(, <operator>)*`,  

Line-scoped directives. Disable and enable operator macros at next line. Works for all blocks at next line.

## Macro API

 *  `createOperatorMacro` — just like `createMacro`, but for operator macros.
 *  `operators` — an object with operator name — corresponding symbol pairs. It's values used as keys in `references` object in macro.

**OR**

 *  `createMacro` — the same function, but works slightly differently.
 *  `operators` — as described above.

**OR**

 *  `createOperatorMacro` — as described above, but passes `references` with canonical operator names as regular keys at object, rather than defined with symbols.

**OR (I prefer this)**

 *  `createMacro` — works as usual for regular macros, but if macro matches operator name, it basses binary expression to macro. So you can defined a macro which works as both regular and operator macro.

````javascript
import { plus } from 'my.macro';
plus(1, 2, 3); // Works as regular macro.
1 + 2 + 3; // Works as operator macro. NB: There are two macro applications.
````

**Comment by kentcdodds** [comment]
Thanks for the explanation. However, while this seems like it could be fairly powerful and flexible, I'm not convinced that this would be a good thing for this plugin nor for people to use in their codebases. I fear it would lead to very complicated code and transformations that would make it harder for people to maintain their codebases.

So I'm going to go ahead and close this. Feel free to fork `babel-plugin-macros` into your own project that supports what you're envisioning to prove me wrong and we can talk about it again if you do. Good luck! And thanks again!
