### ISSUE TITLE
Replace the first example in README with one that doesn't rely on strings

### ISSUE THREAD

**Issue by gaearon** [kentcdodds/babel-plugin-macros#47]
I think the README is still a bit confusing because it uses the `eval` example. Most people will think that's what this plugin is about without reading the rest. Can we use some example with non-string AST transformation?

**Comment by kentcdodds** [comment]
Thanks for bringing this up. I'll fix it up right away :+1:

**Comment by gaearon** [comment]
Maybe some real-world examples of existing macros would help? e.g. Emotion etc

**Comment by kentcdodds** [comment]
Yeah, real-world would be nice. Unfortunately most of the real-world macros I'm aware of are either code-in-strings (like emotion or preval), or are a little harder to grasp/distracting.

I'm thinking that I'll use this as an example: https://github.com/facebookincubator/create-react-app/issues/1792 with a theoretical babel plugin that behaves similar to the webpack loader. Seems practical I think... If you have other suggestions I'd welcome them!

I could also do the `console.scope` one that I have in [the blog post](https://babeljs.io/blog/2017/09/11/zero-config-with-babel-macros) 🤔

**Comment by kentcdodds** [comment]
I think I'll use [`idx.macro`](https://github.com/dralletje/idx.macro) as an example instead

**Comment by kentcdodds** [comment]
Dang it, the `idx` plugin is smart and only applies itself when there's an import of `idx` which is awesome, but unfortunate for the example because it means we can't highlight one of the niceties of using babel-plugin-macros (explicitness). Back to `console.scope` then :)
