### ISSUE TITLE
Support caching the result of macros

### ISSUE THREAD

**Issue by viankakrisna** [kentcdodds/babel-plugin-macros#55]
First thing first: thank you for giving the world this plugin! Sorry I erased the issue template but this is more of a feature request / RFC

I imagine that https://github.com/facebook/create-react-app/issues/3856#issuecomment-358762155 would be a showstopper for people that want to use macros as a loader, limiting the use case of macro itself, I imagine that maybe we could store the result of macros to `node_modules/.cache` and `import` it in the generated code? I'm not sure if that works and that this is the best place to discuss it, but maybe we can add docs for people who want to write macros and cache the results?

disclaimer: I'm a noob in babel and ASTs, even after seeing videos of how to write it i still don't grasp it fully... I just see it as a potential move from webpack's loader to something that is more portable and easier to use.

**Comment by kentcdodds** [comment]
Yes, I would love to see someone create a macro that does this and maybe a tutorial on how to accomplish it (or even a utility lib to help make it work). I don't think I have the time to work on this problem at the moment, but this would definitely be a killer feature and probably wouldn't require a ton of babel/AST knowledge to do!

**Comment by linonetwo** [comment]
Do you mean cache the result so that webpack dev server will reload faster?

I think that has already be done in CRA since I have to manually clear the cache.
```json
    "start": "yarn clear:babel-cache && react-app-rewired start",
    "build": "yarn create-config && yarn clear:babel-cache && react-app-rewired build",
    "clear:babel-cache": "rimraf -rf ./node_modules/.cache/babel-loader/*",
```

**Comment by viankakrisna** [comment]
i mean if the macro is reading a content of a file, like an svg for example, and calling this macro twice in our source code for a same svg file, we're effectively reading and including that content twice in the generated output.

**Comment by kentcdodds** [comment]
Yes, this is a shortcoming of using a babel plugin (which doesn't have a concept of a module system) vs a webpack loader (which treats the entire file as a module). You can solve this issue by creating a module that's responsible for importing the file you want to then using that module everywhere instead of the babel macro everywhere.

**Comment by kentcdodds** [comment]
That said, I do like the workaround idea you proposed so we'll leave this open.

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this as nobody's actively working on it. Feel free to open a new issue if anyone wants to start working on it.
