### ISSUE TITLE
Mock macros

### ISSUE THREAD

**Issue by vinhlh** [kentcdodds/babel-plugin-macros#56]
Problem description:
Sometimes, we would have test cases that need to mock macros.
Mocking this way would be more explicit?
```js
    jest.mock('tagged-translations/macro', () => jest.fn())
...
    t.mockImplementation(
      text => (text === 'all-products' ? `produk-baru` : text)
    )

```
And in order to support this, `babel-plugin-macros` would need to disable some transpilations and make it mockable.
What do you guys think?

**Comment by kentcdodds** [comment]
Hmmm... I'm not certain I understand the use case for mocking `babel-plugin-macros` 🤔 

Testing babel plugins is best done without mocking I think...

**Comment by vinhlh** [comment]
An example use case looks like this:
```js
import t from 'tagged-translations/macro'

const includeStrings = (url, ...strings) =>
  strings.find(str => url.indexOf(str) !== -1)

const routeUrlToCatalogParams = url => {
  if (includeStrings(url, 'special-price', t`special-price`)) {
    return { special_price: true }
  }

  if (includeStrings(url, 'new-products', t`new-products`)) {
    return { new_products: true }
  }

  if (includeStrings(url, 'all-products', t`all-products`)) {
    return { all_products: true }
  }
}
```

```js
jest.mock('tagged-translations/macro', () => jest.fn())
...

  it('should pass all_products into the parameter if the url contains its translation', () => {
    t.mockImplementation(
      text => (text === 'all-products' ? `produk-baru` : text)
    )
    const result = routeUrlToCatalogParams('/women/produk-baru/')
    const expected = { all_products: true }
    expect(result).toEqual(expected)
  })
```

We could implement this test via a global fixture translations.
But defining a local mock would be more explicit way, right 💃

**Comment by kentcdodds** [comment]
Ah! That makes sense!

I'm not sure what changes we could make to this plugin for that to work reliably though... You could just not include the macros plugin in your Babel config when running tests. I think that's probably the best solution...

**Comment by vinhlh** [comment]
Makes sense. Using a global fixture or disabling macros plugin would be good enough 👍 .
