### ISSUE TITLE
How to implement macro with async function inside?

### ISSUE THREAD

**Issue by stereobooster** [kentcdodds/babel-plugin-macros#62]
* `babel-plugin-macros` version: 2.1.0
* `node` version: 8.6
* `npm` (or `yarn`) version: yarn 1.5.1

Relevant code or config

```javascript
```

What you did:

What happened:

Reproduction repository:

https://github.com/stereobooster/lqip.macro

Problem description:

I want to implement [`lqip.macro`](https://github.com/stereobooster/lqip.macro). I'm not sure how to use async `lqip` in `babel-plugin-macros`, which seems to be expecting synchronous code. Am I wrong here? What is the way to work with async functions? Thanks

Suggested solution:

**Comment by kentcdodds** [comment]
Yes, this is a sad limitation to babel transforms. They are completely synchronous. @threepointone told me this crazy idea to make async node code run synchronously. It's going to be slow, but it works like a charm. Here's an example from real code that I'm using at PayPal:

```js
const results = crossSpawn.sync('node', [
  '-e',
  `require("${spundlePath}")("${localesDir}", "${country}", "${locale}", (err, out) => {console.log(JSON.stringify(out))})`,
])
const en = JSON.parse(results.stdout)['en-US']
```

That should give you an idea of how to make it run synchronously. There may be a module for this.

In any case, I think we should either create a utility and expose that from babel-plugin-macros, or (probably better) create a module that makes this easier. What do you think?

**Comment by kentcdodds** [comment]
Unfortunately not. But @hzoo may have some other ideas.

**Comment by stereobooster** [comment]
I did this:

```js
function syncLqip(path) {
  return execSync("node src/lqip.js " + path, { shell: false })
    .toString("utf8")
    .trim();
}
```

**Comment by stereobooster** [comment]
I found workaround for my case. Should we close this ticket or keep open to find general solution?

**Comment by kentcdodds** [comment]
Maybe we could add a link to this issue in the author.md docs file?

**Comment by Zemnmez** [comment]
I've made @kentcdodds solution into a more generic & cleaner micro library: https://github.com/Zemnmez/do-sync

**Comment by kentcdodds** [comment]
Very cool @Zemnmez! Thank you 💯
