### ISSUE TITLE
Allow custom JSX macros

### ISSUE THREAD

**Issue by Andarist** [kentcdodds/babel-plugin-macros#66]
Followup to https://github.com/emotion-js/emotion/issues/673

**Problem description:**

It's not possible at the moment to use macro as custom JSX. 

**Suggested solution:**

I think it should be possible to read jsx pragma and check it against imported macros to see if we should apply macros on them too.

Not sure though if due to babel plugin ordering issue it would be easy to support this use case because jsx transform runs on `Program.enter` & babel macros run on `ImportDeclaration`. It should be possible to switch to `Program.enter` too - but again, plugin ordering might bite us on this.

Also not sure how to support other pragmas with it (to support both jsx macro + preact at the same time).

Thoughts?

**Comment by kentcdodds** [comment]
I honestly am not sure what's best here. I'm afraid that I'd need to see an example implementation with an exploration on what the impact would be before I could make any judgment on whether I'd want to make the change.
