### ISSUE TITLE
Would it be possible to write an apply macro? 

### ISSUE THREAD

**Issue by danielo515** [kentcdodds/babel-plugin-macros#68]
Hello, 

First of all, thanks for this great idea. I really like things that are explicit and clear. You may not how the imported macro works, but you are clear about the fact that it is a macro, I love it. 

After reading the documentation, the babel handbook and some macro examples I'm still not clear if what I want to do is possible. 
I'm using functional programming a lot, and all my functions are curried, which could be a bit cumbersome to call sometimes. For that reason I want to build a small syntactic sugar macro to simulate the $ operator of Haskell. Let me explain it with an example 

```javascript
add $ 11 12
// output
add (11) (12)
```

Ideally I would want to be a le to nest them or at least group arguments with parentheses :

```javascript
compose $ (add $ 11) inc
// output
compose (add (11)) (inc)
```

Do you think such macro is possible? 

Thanks in advance

**Comment by kentcdodds** [comment]
Unfortunately this is not possible. At least not in the way I think you want.

babel-plugin-macros does not allow you to add custom syntax to the language that is not supported by babylon (babel's language parser). If you go to [the babel repl](http://babeljs.io/repl) and try that code out there you'll notice that it doesn't parse.

Sorry.

**Comment by danielo515** [comment]
Thanks for clarification.
I'll try with sugar then.

Thanks
