### ISSUE TITLE
Incorrect package name in exception

### ISSUE THREAD

**Issue by tricoder42** [kentcdodds/babel-plugin-macros#72]
* `babel-plugin-macros` version: 2.3.0

What you did:
Raised an exception in macro from package `@lingui/react.macro`.

What happened:
Message show up with appended help text: `Learn more: https://www.npmjs.com/package/@lingui`

Problem description:
The package name in help text is invalid, it should be 
`Learn more: https://www.npmjs.com/package/@lingui/react.macro`

Suggested solution:
The help text is added [here](https://github.com/kentcdodds/babel-plugin-macros/blob/master/src/index.js#L189)

According to docs, valid macros ends with `/macro`, `/macro.js`, `.macro`, `.macro.js`.
These are possible cases:

NPM Package Name | Macro
--- | ---
package | package/macro
package | package/macro.js
package | package/name.macro
package | package/name.macro.js
package.macro | package.macro
@org/macro | @org/macro
@org/name.macro | @org/name.macro

Looking at this table, we should replace *anything after `/` only if package name (`source`) doesn't start with `@`*

Am I right? Is it possible to import from `@org/package/module/macro`?

**Comment by kentcdodds** [comment]
Hi @tricoder42!

Thanks for the issue. `import macro from '@lingui/react.macro'` should totally work and if it doesn't then that's a bug. Would you be willing to dig into that?
