### ISSUE TITLE
Keep macro import for other plugins

### ISSUE THREAD

**Issue by tricoder42** [kentcdodds/babel-plugin-macros#74]
Hey,
I have an plugin, which is supposed to run on nodes returned from macro. The catch is that I'm also checking imports in the file just to be sure I'm processing the right components.

However, once `babel-plugin-macros` removes an import node, other plugins won't run (obviously, because that node no longer exists).

> One other thing to note is that after your macro has run, babel-plugin-macros will remove the import/require statement for you.

I'm not able to figure out the best solution here:

1. Add option to macro to keep import nodes. Plugin would be added to config as `["macros", { keepImports: true }]` (I'm happy to provide a PR if you give a green light to this)
2. I can't append import node manually after current node, because it would be picked again by `macros` plugin (and probably case infinite loop).
3. I can't extract messages as part of macro (although that would be really cool), because I need to also support users who don't use macro at all (macros basically transform `Trans` from `@lingui/react.macro` to `Trans` from `@lingui/react`, so it's possible to use the lib without macros).

**Comment by kentcdodds** [comment]
I think I'd prefer passing this as an option:

```javascript
module.exports = createMacro(myMacro, {keepImports: true})
```

Either that, maybe we could have a return:

```javascript
function myMacro(/* args */) {
  // ... macro code
  return {keepImport: true}
}
```

What do you think? The later would be even more flexible.

**Comment by tricoder42** [comment]
I was thinking about the second option as well, because right now macros don't return anything. And you're right, this should be a local option not global one - we don't want to break all macros in project just because one of them has special requirements...

I'm gonna prepare a PR.
