### ISSUE TITLE
Using create react app, the errors using babel-macros are very cryptic.

### ISSUE THREAD

**Issue by lifeiscontent** [kentcdodds/babel-plugin-macros#79]
* `babel-plugin-macros` version: whatever react-scripts@beta is using
* `node` version: v8.11.3
* `npm` (or `yarn`) version: 6.2.0

Relevant code or config

when using a macro that loads files from the file system, such as `graphql.macro` it'll just give an error saying `Failed to compile` which is pretty cryptic.

What you did:

Load a file at an invalid path

What happened:

Failed to compile
./src/screens/Dashboard/Projects.js

Reproduction repository:

Problem description: cryptic error messages

Suggested solution: if its possible, make errors a bit more helpful.

**Comment by kentcdodds** [comment]
Interesting... Hmmm... I'm afraid that's not something we can do in this project. We actually do give more helpful error messages. My guess is that this is something that would need to be done in react-scripts or webpack.

Sorry :-/
