### ISSUE TITLE
Feature : Configuration with babel config (.babelrc, ...)

### ISSUE THREAD

**Issue by lucleray** [kentcdodds/babel-plugin-macros#82]
Would it be possible to configure macros directly with the babel config (.babelrc or other babel config) :

```js
// .babelrc
{
  "plugins": ["macros", {
    "taggedTranslations": { 
      "someConfig": {}
    }
  }]
}
```

Then you get it like this in the macro :
```js
const { createMacro } = require('babel-plugin-macros')

const configName = 'taggedTranslations'

module.exports = createMacro(taggedTranslationsMacro, { configName })

function taggedTranslationsMacro({references, state, babel, config}) {
  // config is { someConfig: {} }
}
```

This way, it's easier to test a specific config :
```js
import pluginTester from 'babel-plugin-tester'
import plugin from 'babel-plugin-macros'

pluginTester({
  plugin,
  snapshot: true,
  babelOptions: { filename: __filename },
  tests: [{
    code: `...`,
    babelOptions: {
      taggedTranslations: { someConfigIWantToTest: {} } // i add my config here 🚀
    }
  }],
})
```

**Comment by lucleray** [comment]
Also, this thing could replace cosmiconfig !

https://github.com/kentcdodds/babel-plugin-macros/blob/1785a0fab2c374d1505c49cff1bd38fd541819e2/src/index.js#L216-L220

**Comment by tricoder42** [comment]
@lucleray It sounds good, but we shouldn't replace cosmiconfig. Not all projects have the luxury to edit the Babel config (e.g. projects using Create React App).

I think this is a good alternative to `.babel-plugin-macrosrc` file.

**Comment by lucleray** [comment]
@tricoder42 
I'm completely ok to keep both 🙂

But I'm just going to add a counter-argument (but I don't use create-react-app so what do I know 😅).

You can always eject with create-react-app. If the purpose of this package and create-react-app is to provide zero config with great defaults, then maybe this extra step is a good reminder to users that they should just use the defaults ?

**Comment by tricoder42** [comment]
Ejecting is the worst case scenario. In this case it's a problem to support both styles of configuration.

@kentcdodds What do you think?

**Comment by lucleray** [comment]
@kentcdodds That's all I need, thanks !
