### ISSUE TITLE
macro: decorators

### ISSUE THREAD

**Issue by jadbox** [kentcdodds/babel-plugin-macros#86]
I've been testing out CRA 2.0, but found the lack of decorators frustrating since Mobx heavily recommends them. Is there a current path to use a babel-macro so enable this feature for CRA?

**Comment by tricoder42** [comment]
Could you please show an example of a code using decorators? I'm afraid this might be something what's not possible with macros, because it requires implicit transformation, but I might be wrong.

**Comment by jadbox** [comment]
I'm using Typescript and Mobx-React (https://github.com/mobxjs/mobx-react) for my components... below is a simple example.

```
import { observer } from "mobx-react"

// ---- ESNext syntax with decorators ----
@observer
class TodoView extends React.Component {
    render() {
        return <div>{this.props.todo.title}</div>
    }
}
```

**Comment by tricoder42** [comment]
Unfortunately, macros can't be used to extend the syntax. Macros are always explicit, while new syntax requires plugin which traverses whole AST.

**Comment by jadbox** [comment]
Okay, thanks for the know
