### ISSUE TITLE
Order of application in non-macro transforms chain

### ISSUE THREAD

**Issue by awto** [kentcdodds/babel-plugin-macros#95]
Order of application in non-macro transforms chain
In my macro, I need to covert async generators, but if I simply invoke babel with "preset-env":

```
$ babel --plugins @effectful/es/transform --presets @babel/preset-env index.js
```

All the async generators will be cleared and converted to plain generators. So my macro is applied somewhere between "@babel/plugin-proposal-async-generator-functions" and "@babel/plugin-transform-regenerator" - I don't have async generators but still have plain generators in my macro AST. This sounds like a pretty random and non-deterministic position. There are no definite order and anything can be broken by just adding some merge-preventing plugin in the chain after "babel-plugin-macros".

Adding "passPerPreset:true" solves the problem, but unfortunately this is not an option for zero config tools like Create React App. 

I guess this happens because the next plugins are merged with the main "babel-plugin-macros" pass which simply searches for imports, while the macros are applied after that merged transform is finished for already transformed AST.

Can we make the search as a nested traversal so it is not merged?

**Comment by kentcdodds** [comment]
Hi,

Babel plugin ordering is a bit nuanced I'm afraid. There's not much we can do about this from within this project 😬

https://jamie.build/babel-plugin-ordering.html

**Comment by awto** [comment]
it is not about plugin ordering, plugin application is pretty fine, and it is deterministic, I can tune it in whatever way I want. The ticket is about macro application ordering relating to other plugins, it is non-deterministic, and it sounds like a problem for me, not a nuance.

**Comment by kentcdodds** [comment]
Macros are applied in the order they are imported, but I don't have control over how babel-plugin-macros is applied relative to other babel plugins.

If you believe that I'm mistaken, then feel free to open a pull request (with tests that reveal the issue if possible) and I'll happily give that a review.
