### ISSUE TITLE
Curried function application

### ISSUE THREAD

**Issue by masaeedu** [kentcdodds/babel-plugin-macros#97]
Hi there. This is more of a feature request than a bug report, so I hope you don't mind my not using the template.

I have the following simple library for applying static functions infix:

```js
const Obj = {
  map: f => o => Object.keys(o).reduce((p, k) => ({ ...p, [k]: f(o[k]) }), {})
};

const infix = X => {
  const wrap = x => {
    const methods = Obj.map(f => v => wrap(f(v)(x)))(X);
    return { ...methods, unwrap: x };
  };
  return wrap;
};
```

Which can be used for example like so:

```js
const { infix } = require("@masaeedu/infix")

const F = { "|>": f => x => f(x) } // or equivalently, `"|>": x => x`

const four = infix(F)(1)
  ["|>"](x => x + 1)
  ["|>"](x => x + 2).unwrap
```

which works identically to:

```js
const four = F["|>"](x => x + 2)(F["|>"](x => x + 1)(1))
        // = (x => x)(x => x + 2)((x => x)(x => x + 1)(1))
        // = (x => x + 2)((x => x + 1)(1))
        // = (x => x + 2)(1 + 1)
        // = (1 + 1 + 2)
```

This works fine, but has a runtime cost. I'd like to perform the equivalent desugaring for any invocation of `infix`, and was hoping to be able to use babel-plugin-macros for this.

However right now (if I understand correctly), if `infix` is expressed as a macro, it will only support AST manipulation in the body of the first argument, instead of throughout the `infix(F)(1)...` expression.

Would you be amenable to supporting this sort of use case in addition?

**Comment by kentcdodds** [comment]
I'm not sure I understand what change you want in babel-plugin-macros...

**Comment by masaeedu** [comment]
@kentcdodds When defining `infix` as a macro, I would like to be able to receive and modify all of the AST corresponding to the expression:

```
infix(F)(1)
  ["|>"](x => x + 1)
  ["|>"](x => x + 2).unwrap
```

instead of only receiving and being able to modify the AST corresponding to the expression `F`.

**Comment by kentcdodds** [comment]
Oh, gotcha. Yes, you can definitely do this already. You can get that via the identifier path. Checkout the docs about authoring macros and there are resources for how to traverse the node's relationships (specifically its parent).

Good luck!

**Comment by masaeedu** [comment]
Great, thanks!
